# Generated by Django 5.1.6 on 2025-03-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=250, unique=True)),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/preview/",
                        verbose_name="Изображения - анонс",
                    ),
                ),
                (
                    "detail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/detail/",
                        verbose_name="Изображение - детальной",
                    ),
                ),
                (
                    "preview_content",
                    models.TextField(
                        blank=True,
                        default="Скоро тут будет статья",
                        verbose_name="Текст статьи - анонс",
                    ),
                ),
                (
                    "detail_content",
                    models.TextField(
                        default="Скоро тут будет статья",
                        verbose_name="Текст статьи - детальный",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, verbose_name="Технический режим"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Мой Сайт",
                        max_length=255,
                        verbose_name="Название сайта",
                    ),
                ),
                (
                    "domains",
                    models.TextField(
                        default="example.com",
                        help_text="Разделяйте домены запятыми",
                        verbose_name="Домены",
                    ),
                ),
                (
                    "main_phone",
                    models.CharField(max_length=20, verbose_name="Основной телефон"),
                ),
                ("vk_url", models.URLField(blank=True, verbose_name="ВКонтакте")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Основной Email"),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(
                        default=True, verbose_name="Разрешить индексацию"
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="H:i", max_length=50, verbose_name="Формат времени"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="ru-RU", max_length=10, verbose_name="Локаль"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=250, unique=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название тега"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=250, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/preview/",
                        verbose_name="Изображения - анонс",
                    ),
                ),
                (
                    "detail_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/detail/",
                        verbose_name="Изображение - детальной",
                    ),
                ),
                (
                    "preview_content",
                    models.TextField(
                        blank=True,
                        default="Скоро тут будет статья",
                        verbose_name="Текст статьи - анонс",
                    ),
                ),
                (
                    "detail_content",
                    models.TextField(
                        default="Скоро тут будет статья",
                        verbose_name="Текст статьи - детальный",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок статьи"),
                ),
                ("watched", models.IntegerField(default=0, verbose_name="Просмотры")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="vproger.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="vproger.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "indexes": [
                    models.Index(
                        fields=["-created_at", "is_published"],
                        name="vproger_pos_created_306b21_idx",
                    ),
                    models.Index(fields=["slug"], name="post_slug_idx"),
                ],
            },
        ),
    ]
