# Generated by Django 5.1.6 on 2025-03-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0002_post_from_django_post_post_id_post_vk_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=250, unique=True)),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок статьи"),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="vproger.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
