# Generated by Django 5.1.6 on 2025-03-10 21:41

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0003_alter_post_post_id_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="detail_content_markdown",
            field=markdownx.models.MarkdownxField(
                blank=True,
                default="Скоро тут будет статья",
                verbose_name="Текст статьи - анонс",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post",
                to="vproger.post",
                verbose_name="Пост",
            ),
        ),
    ]
