# Generated by Django 5.1.6 on 2025-03-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0004_post_detail_content_markdown_alter_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="detail_content_markdown",
        ),
    ]
