# Generated by Django 5.1.6 on 2025-03-11 15:29

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0006_post_detail_content_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="detail_content_markdown",
            field=markdownx.models.MarkdownxField(
                blank=True,
                default="Скоро тут будет статья",
                verbose_name="Текст статьи - анонс",
            ),
        ),
    ]
