# Generated by Django 5.1.6 on 2025-03-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0007_alter_post_detail_content_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="detail_content_markdown",
            field=models.TextField(
                blank=True,
                default="Скоро тут будет статья",
                verbose_name="Текст статьи - markdown",
            ),
        ),
    ]
