# Generated by Django 5.1.6 on 2025-03-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0008_alter_post_detail_content_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="seo_canonical",
            field=models.URLField(
                blank=True,
                help_text="Канонический URL (если не установлен, будет использоваться get_absolute_url).",
                null=True,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="seo_description",
            field=models.TextField(
                blank=True,
                help_text="Описание для поисковых систем. Если не заполнено, будет автоматически сформировано из контента.",
                verbose_name="SEO Description",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="seo_keywords",
            field=models.CharField(
                blank=True,
                help_text="Ключевые слова через запятую.",
                max_length=255,
                verbose_name="SEO Keywords",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="Заголовок для поисковых систем. Если не заполнено, будет использоваться title.",
                max_length=255,
                verbose_name="SEO Title",
            ),
        ),
    ]
