# Generated by Django 5.1.6 on 2025-03-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0009_post_seo_canonical_post_seo_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="apple_touch_icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Apple Touch Icon",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_avif",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (AVIF)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_ico",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (ICO)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_png",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (PNG)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_svg",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (SVG)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_webp",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (WebP)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_analytics",
            field=models.TextField(
                blank=True, verbose_name="Google Analytics (код вставки в head)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logo/",
                verbose_name="Логотип (JPG, PNG, WebP, SVG, AVIF)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="manifest_json",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Manifest.json",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mask_icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Safari Mask Icon",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mask_icon_color",
            field=models.CharField(
                default="#000000", max_length=7, verbose_name="Цвет mask-icon"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="theme_color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="Цвет theme-color"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="yandex_metrika",
            field=models.TextField(
                blank=True, verbose_name="Yandex Metrika (код вставки в head)"
            ),
        ),
    ]
