# Generated by Django 5.1.6 on 2025-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0010_sitesettings_apple_touch_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="locale",
            field=models.CharField(
                choices=[
                    ("ru-RU", "Русский (Россия)"),
                    ("en-US", "English (US)"),
                    ("de-DE", "Deutsch (Deutschland)"),
                    ("fr-FR", "Français (France)"),
                    ("es-ES", "Español (España)"),
                    ("zh-CN", "中文 (简体, 中国)"),
                    ("ja-JP", "日本語 (日本)"),
                    ("ar-SA", "العربية (السعودية)"),
                ],
                default="ru-RU",
                max_length=10,
                verbose_name="Локаль",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="time_format",
            field=models.CharField(
                choices=[
                    ("d.m.Y", "31.12.2025"),
                    ("Y-m-d", "2025-12-31"),
                    ("m/d/Y", "12/31/2025"),
                    ("d M Y", "31 Dec 2025"),
                    ("D, d M Y", "Fri, 31 Dec 2025"),
                    ("l, d F Y", "Friday, 31 December 2025"),
                ],
                default="d.m.Y",
                max_length=50,
                verbose_name="Формат даты и времени",
            ),
        ),
    ]
