# Generated by Django 5.1.6 on 2025-03-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vproger", "0011_alter_sitesettings_locale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="favicon_avif",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="favicon_png",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="favicon_svg",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="favicon_webp",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_png_16",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (PNG 16x16)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_png_192",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (PNG 192x192)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_png_32",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (PNG 32x32)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_png_512",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="favicon/",
                verbose_name="Favicon (PNG 512x512)",
            ),
        ),
    ]
