# Generated by Django 5.1.6 on 2025-03-02 19:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooking", "0002_tag_alter_category_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="content",
            field=ckeditor.fields.RichTextField(
                default="Скоро тут будет описание", verbose_name="Текст категории"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(
                default="Скоро тут будет статья", verbose_name="Текст статьи"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
