# Generated by Django 5.1.6 on 2025-03-02 19:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cooking", "0003_alter_category_content_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="content",
            field=tinymce.models.HTMLField(
                default="Скоро тут будет описание", verbose_name="Текст категории"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(
                default="Скоро тут будет статья", verbose_name="Текст статьи"
            ),
        ),
    ]
