# Generated by Django 5.1.6 on 2025-03-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooking", "0004_alter_category_content_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="category",
            name="content",
            field=models.TextField(
                default="Скоро тут будет описание", verbose_name="Текст категории"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                default="Скоро тут будет статья", verbose_name="Текст статьи"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                related_name="posts", to="cooking.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
