# Generated by Django 5.1.6 on 2025-03-04 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=250, unique=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
                (
                    "content",
                    models.TextField(
                        default="Скоро тут будет описание",
                        verbose_name="Текст категории",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=250, unique=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название тега"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=250, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок статьи"),
                ),
                (
                    "content",
                    models.TextField(
                        default="Скоро тут будет статья", verbose_name="Текст статьи"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/",
                        verbose_name="Изображение",
                    ),
                ),
                ("watched", models.IntegerField(default=0, verbose_name="Просмотры")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="posts", to="blog.tag", verbose_name="Теги"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "indexes": [
                    models.Index(
                        fields=["-created_at", "is_published"],
                        name="blog_post_created_155db7_idx",
                    ),
                    models.Index(fields=["slug"], name="post_slug_idx"),
                ],
            },
        ),
    ]
