# Generated by Django 5.1.6 on 2025-03-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="photo",
        ),
        migrations.AddField(
            model_name="post",
            name="detail_content",
            field=models.TextField(
                default="Скоро тут будет статья",
                verbose_name="Текст статьи - детальный",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="detail_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/detail/",
                verbose_name="Изображение - детальной",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="preview_content",
            field=models.TextField(
                default="Скоро тут будет статья", verbose_name="Текст статьи - анонс"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/preview/",
                verbose_name="Изображения - анонс",
            ),
        ),
    ]
