# Generated by Django 5.1.6 on 2025-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_content_remove_post_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="photo",
        ),
        migrations.AddField(
            model_name="category",
            name="detail_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/detail/",
                verbose_name="Изображение - детальной",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/preview/",
                verbose_name="Изображения - анонс",
            ),
        ),
    ]
