# Generated by Django 5.1.6 on 2025-03-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_category_photo_category_detail_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="content",
        ),
        migrations.AddField(
            model_name="category",
            name="detail_content",
            field=models.TextField(
                default="Скоро тут будет статья",
                verbose_name="Текст статьи - детальный",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="preview_content",
            field=models.TextField(
                default="Скоро тут будет статья", verbose_name="Текст статьи - анонс"
            ),
        ),
    ]
