# Generated by Django 5.1.6 on 2025-03-05 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_category_content_category_detail_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Мой сайт",
                        max_length=255,
                        verbose_name="Название сайта",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        default="example.com", max_length=255, verbose_name="Домен"
                    ),
                ),
                (
                    "main_phone",
                    models.CharField(
                        default="+7 (999) 999-99-99",
                        max_length=20,
                        verbose_name="Основной телефон",
                    ),
                ),
                (
                    "vk_url",
                    models.URLField(blank=True, null=True, verbose_name="ВКонтакте"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, null=True, verbose_name="GitHub"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "main_email",
                    models.EmailField(
                        default="info@example.com",
                        max_length=254,
                        verbose_name="Основной email",
                    ),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(
                        default=True, verbose_name="Разрешить индексацию"
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="H:i", max_length=50, verbose_name="Формат времени"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="ru-RU", max_length=10, verbose_name="Локаль"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, verbose_name="Технический режим"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки",
                "verbose_name_plural": "Настройки",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="category",
            name="preview_content",
            field=models.TextField(
                blank=True,
                default="Скоро тут будет статья",
                verbose_name="Текст статьи - анонс",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="post",
            name="preview_content",
            field=models.TextField(
                blank=True,
                default="Скоро тут будет статья",
                verbose_name="Текст статьи - анонс",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog.tag", verbose_name="Теги"
            ),
        ),
    ]
