# Generated by Django 5.1.6 on 2025-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_settings_alter_category_is_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, verbose_name="Технический режим"
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Мой Сайт",
                        max_length=255,
                        verbose_name="Название сайта",
                    ),
                ),
                (
                    "domains",
                    models.TextField(
                        default="example.com",
                        help_text="Разделяйте домены запятыми",
                        verbose_name="Домены",
                    ),
                ),
                (
                    "main_phone",
                    models.CharField(max_length=20, verbose_name="Основной телефон"),
                ),
                ("vk_url", models.URLField(blank=True, verbose_name="ВКонтакте")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Основной Email"),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(
                        default=True, verbose_name="Разрешить индексацию"
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="H:i", max_length=50, verbose_name="Формат времени"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="ru-RU", max_length=10, verbose_name="Локаль"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
            },
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
