# Generated by Django 5.1.6 on 2025-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VKPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
                ("vk_group_id", models.CharField(max_length=50)),
                ("from_django", models.BooleanField(default=False)),
            ],
        ),
    ]
